### ISSUE TITLE
iOS 7.1.0: Start day cannot be chosen when creating a new entry

### ISSUE THREAD

**Issue by alfonsogarciacaro** [toggl/mobile#1595] opened 2016-05-23 14:32 UTC
A user would be able to choose the start day when creating a new entry in v7.1.0, as it was before.

> can no longer choose a start day when creating a new task. Sometimes tasks spill continue past midnight. If I forget to start a task, I now can&#39;t start one beginning on the previous day. 

Case 290782

**Comment by amulware** [comment] 2016-06-08 07:51
Closing as duplicate of #1642 (more info/discussion there).

**Closed by amulware** 2016-06-08 07:51 UTC
Labels: design, ios
