### ISSUE TITLE
Placeholder activation.

### ISSUE THREAD

**Issue by monday8am** [toggl/mobile#654] opened 2015-05-04 08:56 UTC
For some reason is description placeholder always red. Placeholders and lines should be coloured red only if field is active (eg user typing something)

**Comment by masterrr** [comment] 2015-05-16 11:27
@monday8am please test if the issue is still active on your device

**Comment by monday8am** [comment] 2015-05-16 12:27
@masterrr you didn't tested it?

**Comment by masterrr** [comment] 2015-05-16 12:49
@monday8am fully tested on Nexus 5 & emulator, I remember you had different kind of the issue

**Comment by monday8am** [comment] 2015-05-18 09:48
@masterrr for me works ok :+1:

**Comment by masterrr** [comment] 2015-05-18 13:31
Fixed by https://github.com/toggl/mobile/issues/666

**Closed by masterrr** 2015-05-18 13:31 UTC
Labels: 3h, android, design
