### ISSUE TITLE
Start/Stop button appears in other fragments besides home.

### ISSUE THREAD

**Issue by taavirehemagi** [toggl/mobile#611] opened 2015-04-28 08:14 UTC
Make it disappear when navigated to Feedback or Settings page.

**Comment by monday8am** [comment] 2015-04-28 15:08
closed by #618

**Comment by monday8am** [comment] 2015-04-30 11:34
@taavirehemagi if you start a TE the time label is visible in other screens. Please, check all implementation ( I think Start - Stop time disappeared for a while but I can't reproduce it)

**Comment by taavirehemagi** [comment] 2015-04-30 11:35
Umm, when the timer is running, the duration should show everywhere in the app. Shouldn't it?

**Comment by monday8am** [comment] 2015-04-30 11:44
ok. something more that we have to ask.

**Comment by monday8am** [comment] 2015-04-30 11:46
Keep hidden for the moment (like previous version), later we can gather more opinions.

**Closed** 2015-04-30 13:55 UTC
Labels: 3h, android, bug
